name: Formatting

on:
  push:
    branches:
      - 'master'
      - 'staging**'
  pull_request:
    branches:
      '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # formatting and basic install on cpu-only machine
  formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - id: setup-venv
        uses: ./.github/workflows/setup-venv

      - name: Install deepscale
        run: |
          pip install .[dev,autotuning]
          ds_report

      - name: Formatting checks
        run: |
           pre-commit run --all-files